CREATE ROLE IF NOT EXISTS urbechan WITH LOGIN PASSWORD :password;

DROP DATABASE IF EXISTS urbechan;
CREATE DATABASE urbechan;

ALTER DATABASE urbechan OWNER TO urbechan;
GRANT ALL PRIVILEGES ON DATABASE urbechan TO urbechan;
